dset_name: activitynet
clip_length: 2
train_path:  /home/gfj/lighthouse-main/data/activitynet/activitynet_train_release.jsonl
eval_path:  /home/gfj/lighthouse-main/data/activitynet/activitynet_val_release.jsonl