dset_name: activitynet
clip_length: 2
train_path:  /home/gfj/lighthouse-main/data/activitynet/activitynet_train_release.jsonl
eval_path:  /home/gfj/lighthouse-main/data/activitynet/activitynet_val_release.jsonl

short_memory_len : 8
long_memory_sample_len: 64
future_memory_sample_len: 0

max_v_l: -1
max_q_l: 100
# max_v_l: 500
# max_q_l: 100

compress_len: 16