dset_name: activitynet
clip_length: 2
train_path:  /home/gfj/lighthouse-main/data/activitynet/activitynet_train_release.jsonl
eval_path:  /home/gfj/lighthouse-main/data/activitynet/activitynet_val_release.jsonl

short_memory_len : 8
long_memory_sample_len: 64
future_memory_sample_len: 16

weight_alpha: 0.5
attn_weight: 0.3

lr: 0.0005 # 0.0001-> AdamW，和bsz等比例调整
# lr_drop: 40
max_v_l: -1
max_q_l: 100
# max_v_l: 500
# max_q_l: 100

# eval_epoch_interval: 2

use_vid_compression: True
use_inter_memory: True

compress_len: 16