seed: 2023  
device: 'cuda'
num_workers: 0
# 这几个供ol模型初始化设置num_queries使用，需要与evaluate.py文件中的start_inferrence函数的dataset_config参数保持一致
# short_memory_len : 8
# long_memory_sample_len: 32
# future_memory_sample_len: 0

weight_alpha: 0.5

lr: 0.0008 # 0.0001-> AdamW，和bsz等比例调整
lr_drop: 100  # 400 按照epoch比例调整  
wd: 0.0001 
n_epoch: 50 # 200
max_es_cnt: 200
bsz: 256 # 32
eval_bsz: 100
grad_clip: 0.1
max_q_l: 32
max_v_l: 75
max_windows: 5
clip_length: 1
eval_epoch_interval: 1

position_embedding: "sine"
enc_layers: 2
dec_layers: 2
dim_feedforward: 1024
hidden_dim: 256
input_dropout: 0.5
dropout: 0.1
nheads: 8
num_queries: 10

n_input_proj: 2
saliency_margin: 0.2
span_loss_type: "l1"
set_cost_span: 10
set_cost_giou: 1
set_cost_class: 4
span_loss_coef: 10
giou_loss_coef: 1
label_loss_coef: 4

eos_coef: 0.1
start_label_loss_coef: 10
middle_label_loss_coef: 10
end_label_loss_coef: 10
saliency_loss_coef: 5   

lw_saliency: 1



ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
eval_split_name: val
aux_loss: True

model_ema: False
ema_decay: 0.9
results_dir: results


